site_name: MeCabOnigiri
site_description: mecab-python3 wrapper
site_author: uehara1414
repo_url: https://github.com/uehara1414/MeCabOnigiri

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
